# Generated by Django 4.1.4 on 2023-11-22 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatgbt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('context', models.TextField()),
                ('segment_text', models.TextField()),
                ('segment_key', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('video_url', models.URLField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1024)),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatgbt.segment')),
            ],
        ),
    ]
