# Generated by Django 4.1.4 on 2023-11-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgbt', '0002_segment_video_segmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='segment',
            field=models.ManyToManyField(blank=True, related_name='videos', to='chatgbt.segment'),
        ),
    ]
