# Generated by Django 4.1.4 on 2023-11-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgbt', '0003_video_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Video', max_length=256),
        ),
        migrations.AlterField(
            model_name='video',
            name='segment',
            field=models.ManyToManyField(blank=True, related_name='segment', to='chatgbt.segment'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
