# Generated by Django 4.1.4 on 2023-11-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgbt', '0006_alter_segmentimage_segment_alter_video_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='style',
            field=models.CharField(default='Style', max_length=256),
        ),
    ]
