# Generated by Django 4.1.4 on 2023-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrflogi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='locale',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
