# Generated by Django 4.1.4 on 2023-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrflogi', '0002_qrcode_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='domain',
            field=models.URLField(null=True),
        ),
    ]
