# Generated by Django 4.1.4 on 2023-04-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrflogi', '0003_alter_qrcode_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
