# Generated by Django 4.1.4 on 2023-11-20 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_used', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, null=True)),
                ('network_id', models.IntegerField(blank=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('stripe_planproduct_id', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('stripe_connect', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('stripe_pm', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('account_stripe_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('stripe_login_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('account_connect_status', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('account_stripe_KYC_status', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_profile', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ChatGPTProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_used', models.BigIntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.profile')),
            ],
        ),
    ]
