# Generated by Django 4.1.4 on 2023-11-20 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_stripeprofile_chatgptprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatgbt_profile', to='users.profile'),
        ),
    ]
