# Generated by Django 4.1.4 on 2023-11-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_chatgptprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tokens_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
