# Generated by Django 4.1.4 on 2023-11-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_tokens_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=700, null=True)),
                ('number', models.TextField(blank=True, max_length=700, null=True)),
                ('first_line', models.TextField(blank=True, max_length=700, null=True)),
                ('second_line', models.TextField(blank=True, max_length=700, null=True)),
                ('town', models.TextField(blank=True, max_length=700, null=True)),
                ('city', models.TextField(blank=True, max_length=700, null=True)),
                ('state', models.TextField(blank=True, max_length=700, null=True)),
                ('zipcode', models.TextField(blank=True, max_length=700, null=True)),
                ('additional_info', models.TextField(blank=True, max_length=700, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoryTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_used', models.BigIntegerField(blank=True, null=True)),
                ('tokens_limit', models.BigIntegerField(blank=True, null=True)),
                ('tokens_balance', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token_used',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tokens_limit',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='address', to='users.address'),
        ),
    ]
