# Generated by Django 4.0.1 on 2022-02-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stuart_delivery_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
