# Generated by Django 4.1.dev20220131011451 on 2022-01-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_person_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
