# Generated by Django 4.1.dev20220131011451 on 2022-01-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_name_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
