# Generated by Django 4.1.dev20220201010710 on 2022-02-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='companyname',
            field=models.CharField(default='Company Name', max_length=255),
        ),
        migrations.AddField(
            model_name='establishment',
            name='phone',
            field=models.CharField(default='07890655555', max_length=100),
        ),
        migrations.AddField(
            model_name='establishment',
            name='surname',
            field=models.CharField(default='Surname', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='07890655555', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='Surname', max_length=255),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(default='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Name', max_length=255),
        ),
    ]
