# Generated by Django 4.0.1 on 2022-02-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_establishment_companyname_establishment_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stuart_collection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stuart_delivery_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stuart_delivery_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stuart_tracking_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
