# Generated by Django 4.0.1 on 2022-02-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_order_stuart_collection_order_stuart_delivery_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stuart_pickup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
