# Generated by Django 4.0.1 on 2022-02-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_order_stuart_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stuart_collection',
        ),
        migrations.AddField(
            model_name='order',
            name='stuart_delivery_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stuart_delivery_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
