# Generated by Django 4.0.1 on 2022-02-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_order_stuart_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Provider', max_length=255)),
                ('websocket', models.TextField(blank=True, default='WebsocketURL', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='stuart_delivery_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='small', max_length=50),
            preserve_default=False,
        ),
    ]
